#***********************************************************************
#                 RCS INFO
#
#*  @(#)  $RCSfile: Makefile,v $
#*  @(#)  $Revision: 1.2 $
#*  @(#)  $Date: 1999/05/07 15:37:27 $
#*  @(#)  $Author: taxiadm $
#*  @(#)  $Source: /taxi-scan/taxi_proj/cvs/taxi-scan/src/forms/english/Makefile,v $
#*
#*  Copyright (c) 1994 - MobileSoft Consulting, Inc. Woodinville WA
#*
#***********************************************************************/
#ident "@(#) head:$RCSfile: Makefile,v $	$Revision: 1.2 $"
#
#static char rcsid[] = "$Id: Makefile,v 1.2 1999/05/07 15:37:27 taxiadm Exp $";

B=sformbld 

all : acad.frm account.frm address.frm attr.frm callh.frm calls.frm canmsg.frm \
      driver.frm emerg.frm error.frm excgrp.frm exctype.frm fleet.frm \
      help.frm holiday.frm indv.frm localty.frm mailbox.frm menu.frm msglog.frm \
      placenm.frm profile.frm rate.frm rptmsg.frm seal.frm stat.frm \
      statdrv.frm stats.frm statusr.frm strname.frm strtype.frm \
      subcall.frm subzone.frm syscntl.frm unzoned.frm vehicle.frm zone.frm cust.frm \
      receipts.frm card_type.frm bad_card.frm gps_params.frm veh_cmsg.frm

gps_params.frm : gps_params.per
	$(B) gps_params.per

receipts.frm : receipts.per
	$(B) receipts.per

card_type.frm : card_type.per
	$(B) card_type.per

bad_card.frm : bad_card.per
	$(B) bad_card.per

acad.frm : acad.per
	$(B) acad.per

account.frm : account.per
	$(B) account.per

address.frm : address.per
	$(B) address.per

attr.frm : attr.per
	$(B) attr.per

callh.frm : callh.per
	$(B) callh.per

calls.frm : calls.per
	$(B) calls.per

canmsg.frm : canmsg.per
	$(B) canmsg.per

driver.frm : driver.per
	$(B) driver.per

emerg.frm : emerg.per
	$(B) emerg.per

error.frm : error.per
	$(B) error.per

excgrp.frm : excgrp.per
	$(B) excgrp.per

exctype.frm : exctype.per
	$(B) exctype.per

fleet.frm : fleet.per
	$(B) fleet.per

help.frm : help.per
	$(B) help.per

holiday.frm : holiday.per
	$(B) holiday.per

indv.frm : indv.per
	$(B) indv.per

localty.frm : localty.per
	$(B) localty.per

mailbox.frm : mailbox.per
	$(B) mailbox.per

menu.frm : menu.per
	$(B) menu.per 

msglog.frm : msglog.per 
	$(B) msglog.per 

placenm.frm : placenm.per
	$(B) placenm.per

profile.frm : profile.per
	$(B) profile.per

rate.frm : rate.per
	$(B) rate.per

rptmsg.frm : rptmsg.per
	$(B) rptmsg.per

seal.frm : seal.per
	$(B) seal.per

stat.frm : stat.per
	$(B) stat.per

statdrv.frm : statdrv.per
	$(B) statdrv.per

stats.frm : stats.per
	$(B) stats.per

statusr.frm : statusr.per
	$(B) statusr.per

strname.frm : strname.per
	$(B) strname.per

strtype.frm : strtype.per
	$(B) strtype.per

subcall.frm : subcall.per
	$(B) subcall.per

subzone.frm : subzone.per
	$(B) subzone.per

syscntl.frm : syscntl.per
	$(B) syscntl.per

unzoned.frm : unzoned.per
	$(B) unzoned.per

vehicle.frm : vehicle.per
	$(B) vehicle.per

zone.frm : zone.per
	$(B) zone.per

cust.frm : cust.per
	$(B) cust.per

veh_cmsg.frm : veh_cmsg.per
	$(B) veh_cmsg.per
