						/* definitions for rows and columns for entry of fields on a SUSPEND_SCR */
#define		D_FLEET_ROW		3
#define		D_FLEET_COL		14
#define		D_VEH_ROW		5
#define		D_VEH_COL		14	
#define		D_DRV_COL		38
#define         D_CLEAR_SUSP_COL        75
#define		D_SUSP_ROW		7
#define		D_SUSP_FROM_DATE_COL	52
#define		D_SUSP_FROM_TIME_COL	64
#define		D_SUSP_TO_DATE_COL	76
#define		D_SUSP_TO_TIME_COL	88
#define		D_PASS_ROW		9
#define		D_PASS_COL		48
#define		D_DEL_ROW		10
#define		D_DEL_COL		48
#define		D_TYPEX_ROW		11
#define		D_TYPEX_COL		48
#define		D_REASON_ROW		13
#define		D_REASON_COL		55
#define		D_MSG1_ROW		15
#define		D_MSG_COL		24
#define		D_MSG2_ROW		16
#define		D_MSG3_ROW		17
						/* max characters for each field */
#define		CHARS_FLEET		1
#define		CHARS_VEH		4
#define		CHARS_DRV		6
#define		CHARS_SUSP_DATE		9
#define		CHARS_SUSP_TIME		6
#define		CHARS_Y_N_FLAG		1
#define		CHARS_REASON		24
#define		CHARS_MSG		32
						/* define field positions */
#define		F_FLEET			1
#define		F_VEH			2
#define		F_DRV			3
#define		F_CLEAR_PASS_SUSP	4
#define		F_CLEAR_DEL_SUSP	5
#define		F_CLEAR_X_SUSP		6
#define		F_SUSP_PASS_Y_N		7
#define		F_SUSP_PASS_FROM_DATE	8
#define		F_SUSP_PASS_FROM_TIME	9
#define		F_SUSP_PASS_TO_DATE	10
#define		F_SUSP_PASS_TO_TIME	11
#define		F_SUSP_DEL_Y_N		12
#define		F_SUSP_DEL_FROM_DATE	13
#define		F_SUSP_DEL_FROM_TIME	14
#define		F_SUSP_DEL_TO_DATE	15
#define		F_SUSP_DEL_TO_TIME	16
#define		F_SUSP_X_Y_N		17
#define		F_SUSP_X_FROM_DATE	18
#define		F_SUSP_X_FROM_TIME	19
#define		F_SUSP_X_TO_DATE	20
#define		F_SUSP_X_TO_TIME	21
#define		F_REASON		22
#define		F_MSG1			23
#define		F_MSG2			24
#define		F_MSG3			25
