/***********************************************************************
*                 RCS INFO
*
*  @(#)  $RCSfile: Hist_cmt_private.h,v $
*  @(#)  $Revision: 1.4 $
*  @(#)  $Date: 1998/03/13 18:14:11 $
*  @(#)  $Author: taxiadm $
*  @(#)  $Source: /taxi-scan/taxi_proj/cvs/taxi-scan/src/include/Hist_cmt_private.h,v $
*
*  Copyright (c) 1994 - MobileSoft Consulting, Inc. Woodinville WA
*
***********************************************************************/
#ident "@(#) head:$RCSfile: Hist_cmt_private.h,v $	$Revision: 1.4 $"

/*******************************************************************************
 *                            HISTORY COMMENT  LOG                             *
 *******************************************************************************/

/*******************************************************************************
 *         This file will contain a record for each history comment             *
 *         generated by the User Interface modules. 
 *******************************************************************************/

#ifndef HIST_CMT_H
#define HIST_CMT_H

#include <isam.h>
#define HIST_TEXT_LEN   30
typedef struct cisam_hc
{
               int        comment_id;
	       int     next_part;             
	       int	call_nbr;          
	       char    text[HIST_TEXT_LEN+1];         
	       int	dt_tm;
} HIST_CMT_REC;

#ifdef KEY_SRC
struct keydesc hc_key1= {
         ISNODUPS,
         1,
         {0,LONGSIZE,LONGTYPE},
};
/* call_nbr, dt_tm */
struct keydesc hc_key2= {
  ISDUPS,
  1,
  { {8, LONGSIZE, LONGTYPE} ,
    {42,LONGSIZE, LONGTYPE} },
};
#else
extern struct keydesc hc_key1, hc_key2;
#endif

#endif
