/***********************************************************************
*                 RCS INFO
*
*  @(#)  $RCSfile: res_per_m_strdefs.h,v $
*  @(#)  $Revision: 1.2 $
*  @(#)  $Date: 1996/09/06 13:50:11 $
*  @(#)  $Author: jwelch $
*  @(#)  $Source: /taxi-scan/taxi_proj/cvs/taxi-scan/src/include/res_per_m_strdefs.h,v $
*
*  Copyright (c) 1994 - MobileSoft Consulting, Inc. Woodinville WA
*
***********************************************************************/
#ident "@(#) head:$RCSfile: res_per_m_strdefs.h,v $	$Revision: 1.2 $"

#ifdef INTERNATIONAL

#ifndef INTER_INCLUDES
#include <nl_types.h>
#include <locale.h>
#define INTER_INCLUDES
#endif

#ifdef DECLARING
nl_catd  RES_PER_MAINT_m_catd;
#else
extern nl_catd RES_PER_MAINT_m_catd;
#endif

nl_catd catopen();
char    *catgets();
char    *m_catgets();

#else

#define catgets( catd, set_num, msg_num, s )	s
#define m_catgets( catd, set_num, msg_num, s )	s
#define catclose( a )
#define open_catalog( a, b, c, d )
#define setlocale( a, b )

#endif

#ifdef INTERNATIONAL

#define RES_PER_MAINT_SET       (1)

#define RES_PER_MAINT_START     (1)
#define	RES_PER_MAINT_1		(RES_PER_MAINT_START + 0)
#define	RES_PER_MAINT_2		(RES_PER_MAINT_START + 1)
#define	RES_PER_MAINT_3		(RES_PER_MAINT_START + 2)
#define	RES_PER_MAINT_4		(RES_PER_MAINT_START + 3)
#define	RES_PER_MAINT_5		(RES_PER_MAINT_START + 4)
#define	RES_PER_MAINT_6		(RES_PER_MAINT_START + 5)
#define	RES_PER_MAINT_7		(RES_PER_MAINT_START + 6)
#define	RES_PER_MAINT_8		(RES_PER_MAINT_START + 7)
#define	RES_PER_MAINT_9		(RES_PER_MAINT_START + 8)
#define	RES_PER_MAINT_10		(RES_PER_MAINT_START + 9)
#define	RES_PER_MAINT_11		(RES_PER_MAINT_START + 10)
#define	RES_PER_MAINT_12		(RES_PER_MAINT_START + 11)
#define	RES_PER_MAINT_13		(RES_PER_MAINT_START + 12)
#define	RES_PER_MAINT_14		(RES_PER_MAINT_START + 13)
#define	RES_PER_MAINT_15		(RES_PER_MAINT_START + 14)
#define	RES_PER_MAINT_16		(RES_PER_MAINT_START + 15)
#define	RES_PER_MAINT_17		(RES_PER_MAINT_START + 16)
#define	RES_PER_MAINT_18		(RES_PER_MAINT_START + 17)
#define	RES_PER_MAINT_19		(RES_PER_MAINT_START + 18)
#define	RES_PER_MAINT_20		(RES_PER_MAINT_START + 19)
#define	RES_PER_MAINT_21		(RES_PER_MAINT_START + 20)
#define	RES_PER_MAINT_22		(RES_PER_MAINT_START + 21)
#define	RES_PER_MAINT_23		(RES_PER_MAINT_START + 22)
#define	RES_PER_MAINT_24		(RES_PER_MAINT_START + 23)
#define	RES_PER_MAINT_25		(RES_PER_MAINT_START + 24)
#define	RES_PER_MAINT_26		(RES_PER_MAINT_START + 25)
#define	RES_PER_MAINT_27		(RES_PER_MAINT_START + 26)
#define	RES_PER_MAINT_28		(RES_PER_MAINT_START + 27)
#define	RES_PER_MAINT_29		(RES_PER_MAINT_START + 28)
#define	RES_PER_MAINT_30		(RES_PER_MAINT_START + 29)
#define	RES_PER_MAINT_31		(RES_PER_MAINT_START + 30)
#define	RES_PER_MAINT_32		(RES_PER_MAINT_START + 31)
#define	RES_PER_MAINT_33		(RES_PER_MAINT_START + 32)
#define	RES_PER_MAINT_34		(RES_PER_MAINT_START + 33)
#define	RES_PER_MAINT_35		(RES_PER_MAINT_START + 34)
#define	RES_PER_MAINT_36		(RES_PER_MAINT_START + 35)
#define	RES_PER_MAINT_37		(RES_PER_MAINT_START + 36)
#define	RES_PER_MAINT_38		(RES_PER_MAINT_START + 37)
#define	RES_PER_MAINT_39		(RES_PER_MAINT_START + 38)
#define	RES_PER_MAINT_40		(RES_PER_MAINT_START + 39)
#define	RES_PER_MAINT_41		(RES_PER_MAINT_START + 40)
#define	RES_PER_MAINT_42		(RES_PER_MAINT_START + 41)
#define	RES_PER_MAINT_43		(RES_PER_MAINT_START + 42)
#define	RES_PER_MAINT_44		(RES_PER_MAINT_START + 43)
#define	RES_PER_MAINT_45		(RES_PER_MAINT_START + 44)
#define	RES_PER_MAINT_46		(RES_PER_MAINT_START + 45)
#define	RES_PER_MAINT_47		(RES_PER_MAINT_START + 46)
#define	RES_PER_MAINT_48		(RES_PER_MAINT_START + 47)
#define	RES_PER_MAINT_49		(RES_PER_MAINT_START + 48)
#define	RES_PER_MAINT_50		(RES_PER_MAINT_START + 49)
#define	RES_PER_MAINT_51		(RES_PER_MAINT_START + 50)
#define	RES_PER_MAINT_52		(RES_PER_MAINT_START + 51)
#define	RES_PER_MAINT_53		(RES_PER_MAINT_START + 52)
#define	RES_PER_MAINT_54		(RES_PER_MAINT_START + 53)
#define	RES_PER_MAINT_55		(RES_PER_MAINT_START + 54)
#define	RES_PER_MAINT_56		(RES_PER_MAINT_START + 55)
#define	RES_PER_MAINT_57		(RES_PER_MAINT_START + 56)
#define	RES_PER_MAINT_58		(RES_PER_MAINT_START + 57)
#define	RES_PER_MAINT_59		(RES_PER_MAINT_START + 58)
#define	RES_PER_MAINT_60		(RES_PER_MAINT_START + 59)
#define	RES_PER_MAINT_61		(RES_PER_MAINT_START + 60)
#define	RES_PER_MAINT_62		(RES_PER_MAINT_START + 61)
#define	RES_PER_MAINT_63		(RES_PER_MAINT_START + 62)
#define	RES_PER_MAINT_64		(RES_PER_MAINT_START + 63)
#define	RES_PER_MAINT_65		(RES_PER_MAINT_START + 64)
#define	RES_PER_MAINT_66		(RES_PER_MAINT_START + 65)
#define	RES_PER_MAINT_67		(RES_PER_MAINT_START + 66)
#define	RES_PER_MAINT_68		(RES_PER_MAINT_START + 67)
#define	RES_PER_MAINT_69		(RES_PER_MAINT_START + 68)
#define	RES_PER_MAINT_70		(RES_PER_MAINT_START + 69)
#define	RES_PER_MAINT_71		(RES_PER_MAINT_START + 70)
#define	RES_PER_MAINT_72		(RES_PER_MAINT_START + 71)
#define	RES_PER_MAINT_73		(RES_PER_MAINT_START + 72)
#define	RES_PER_MAINT_74		(RES_PER_MAINT_START + 73)
#define	RES_PER_MAINT_75		(RES_PER_MAINT_START + 74)
#define	RES_PER_MAINT_76		(RES_PER_MAINT_START + 75)
#define	RES_PER_MAINT_77		(RES_PER_MAINT_START + 76)
#define	RES_PER_MAINT_78		(RES_PER_MAINT_START + 77)
#define	RES_PER_MAINT_79		(RES_PER_MAINT_START + 78)
#define	RES_PER_MAINT_80		(RES_PER_MAINT_START + 79)
#define	RES_PER_MAINT_81		(RES_PER_MAINT_START + 80)
#define	RES_PER_MAINT_82		(RES_PER_MAINT_START + 81)
#define	RES_PER_MAINT_83		(RES_PER_MAINT_START + 82)
#define	RES_PER_MAINT_84		(RES_PER_MAINT_START + 83)
#define	RES_PER_MAINT_85		(RES_PER_MAINT_START + 84)
#define	RES_PER_MAINT_86		(RES_PER_MAINT_START + 85)
#define	RES_PER_MAINT_87		(RES_PER_MAINT_START + 86)
#define	RES_PER_MAINT_88		(RES_PER_MAINT_START + 87)
#define	RES_PER_MAINT_89		(RES_PER_MAINT_START + 88)
#define	RES_PER_MAINT_90		(RES_PER_MAINT_START + 89)
#define	RES_PER_MAINT_91		(RES_PER_MAINT_START + 90)
#define	RES_PER_MAINT_92		(RES_PER_MAINT_START + 91)
#define	RES_PER_MAINT_93		(RES_PER_MAINT_START + 92)
#define	RES_PER_MAINT_94		(RES_PER_MAINT_START + 93)
#define	RES_PER_MAINT_95		(RES_PER_MAINT_START + 94)
#define	RES_PER_MAINT_96		(RES_PER_MAINT_START + 95)
#define	RES_PER_MAINT_97		(RES_PER_MAINT_START + 96)
#define	RES_PER_MAINT_98		(RES_PER_MAINT_START + 97)
#define	RES_PER_MAINT_99		(RES_PER_MAINT_START + 98)
#define	RES_PER_MAINT_100		(RES_PER_MAINT_START + 99)
#define	RES_PER_MAINT_101		(RES_PER_MAINT_START + 100)
#define	RES_PER_MAINT_102		(RES_PER_MAINT_START + 101)
#define	RES_PER_MAINT_103		(RES_PER_MAINT_START + 102)
#define	RES_PER_MAINT_104		(RES_PER_MAINT_START + 103)
#define	RES_PER_MAINT_105		(RES_PER_MAINT_START + 104)
#define	RES_PER_MAINT_106		(RES_PER_MAINT_START + 105)
#define	RES_PER_MAINT_107		(RES_PER_MAINT_START + 106)
#define	RES_PER_MAINT_108		(RES_PER_MAINT_START + 107)
#define	RES_PER_MAINT_109		(RES_PER_MAINT_START + 108)
#define	RES_PER_MAINT_110		(RES_PER_MAINT_START + 109)
#define	RES_PER_MAINT_111		(RES_PER_MAINT_START + 110)
#define	RES_PER_MAINT_112		(RES_PER_MAINT_START + 111)
#define	RES_PER_MAINT_113		(RES_PER_MAINT_START + 112)
#define	RES_PER_MAINT_114		(RES_PER_MAINT_START + 113)
#define	RES_PER_MAINT_115		(RES_PER_MAINT_START + 114)
#define	RES_PER_MAINT_116		(RES_PER_MAINT_START + 115)
#define	RES_PER_MAINT_117		(RES_PER_MAINT_START + 116)
#define	RES_PER_MAINT_118		(RES_PER_MAINT_START + 117)
#define	RES_PER_MAINT_119		(RES_PER_MAINT_START + 118)
#define	RES_PER_MAINT_120		(RES_PER_MAINT_START + 119)
#define	RES_PER_MAINT_121		(RES_PER_MAINT_START + 120)
#define	RES_PER_MAINT_122		(RES_PER_MAINT_START + 121)
#define	RES_PER_MAINT_123		(RES_PER_MAINT_START + 122)
#define	RES_PER_MAINT_124		(RES_PER_MAINT_START + 123)
#define	RES_PER_MAINT_125		(RES_PER_MAINT_START + 124)
#define	RES_PER_MAINT_126		(RES_PER_MAINT_START + 125)
#define	RES_PER_MAINT_127		(RES_PER_MAINT_START + 126)
#define	RES_PER_MAINT_128		(RES_PER_MAINT_START + 127)
#define	RES_PER_MAINT_129		(RES_PER_MAINT_START + 128)
#define	RES_PER_MAINT_130		(RES_PER_MAINT_START + 129)
#define	RES_PER_MAINT_131		(RES_PER_MAINT_START + 130)
#define	RES_PER_MAINT_132		(RES_PER_MAINT_START + 131)
#define	RES_PER_MAINT_133		(RES_PER_MAINT_START + 132)
#define	RES_PER_MAINT_134		(RES_PER_MAINT_START + 133)
#define	RES_PER_MAINT_135		(RES_PER_MAINT_START + 134)
#define	RES_PER_MAINT_136		(RES_PER_MAINT_START + 135)
#define	RES_PER_MAINT_137		(RES_PER_MAINT_START + 136)
#define	RES_PER_MAINT_138		(RES_PER_MAINT_START + 137)
#define	RES_PER_MAINT_139		(RES_PER_MAINT_START + 138)
#define	RES_PER_MAINT_140		(RES_PER_MAINT_START + 139)
#define	RES_PER_MAINT_141		(RES_PER_MAINT_START + 140)
#define	RES_PER_MAINT_END		(RES_PER_MAINT_START + 140)

#endif
