/***********************************************************************
*                 RCS INFO
*
*  @(#)  $RCSfile: seasons_m_strdefs.h,v $
*  @(#)  $Revision: 1.3 $
*  @(#)  $Date: 1996/09/20 12:45:44 $
*  @(#)  $Author: jwelch $
*  @(#)  $Source: /taxi-scan/taxi_proj/cvs/taxi-scan/src/include/seasons_m_strdefs.h,v $
*
*  Copyright (c) 1994 - MobileSoft Consulting, Inc. Woodinville WA
*
***********************************************************************/
#ident "@(#) head:$RCSfile: seasons_m_strdefs.h,v $	$Revision: 1.3 $"

#ifdef INTERNATIONAL

#ifndef INTER_INCLUDES
#include <nl_types.h>
#include <locale.h>
#define INTER_INCLUDES
#endif

#ifdef DECLARING
nl_catd SEASONS_MAINT_m_catd;
#else
extern nl_catd SEASONS_MAINT_m_catd;
#endif

nl_catd catopen();
char    *catgets();
char    *m_catgets();

#else
/*
 * no international text	
 */

#define catgets( catd, set_num, msg_num, s )	s
#define m_catgets( catd, set_num, msg_num, s )	s
#define	catclose( a )
#define setlocale(a, b)	
#define open_catalog(a, b, c, d)

#endif

#ifdef INTERNATIONAL

#define  SEASONS_MAINT_SET         (1)

#define	SEASONS_MAINT_START		(1)
#define	SEASONS_MAINT_1		(SEASONS_MAINT_START + 0)
#define	SEASONS_MAINT_2		(SEASONS_MAINT_START + 1)
#define	SEASONS_MAINT_3		(SEASONS_MAINT_START + 2)
#define	SEASONS_MAINT_4		(SEASONS_MAINT_START + 3)
#define	SEASONS_MAINT_5		(SEASONS_MAINT_START + 4)
#define	SEASONS_MAINT_6		(SEASONS_MAINT_START + 5)
#define	SEASONS_MAINT_7		(SEASONS_MAINT_START + 6)
#define	SEASONS_MAINT_8		(SEASONS_MAINT_START + 7)
#define	SEASONS_MAINT_9		(SEASONS_MAINT_START + 8)
#define	SEASONS_MAINT_10		(SEASONS_MAINT_START + 9)
#define	SEASONS_MAINT_11		(SEASONS_MAINT_START + 10)
#define	SEASONS_MAINT_12		(SEASONS_MAINT_START + 11)
#define	SEASONS_MAINT_13		(SEASONS_MAINT_START + 12)
#define	SEASONS_MAINT_14		(SEASONS_MAINT_START + 13)
#define	SEASONS_MAINT_15		(SEASONS_MAINT_START + 14)
#define	SEASONS_MAINT_16		(SEASONS_MAINT_START + 15)
#define	SEASONS_MAINT_17		(SEASONS_MAINT_START + 16)
#define	SEASONS_MAINT_18		(SEASONS_MAINT_START + 17)
#define	SEASONS_MAINT_19		(SEASONS_MAINT_START + 18)
#define	SEASONS_MAINT_20		(SEASONS_MAINT_START + 19)
#define	SEASONS_MAINT_21		(SEASONS_MAINT_START + 20)
#define	SEASONS_MAINT_22		(SEASONS_MAINT_START + 21)
#define	SEASONS_MAINT_23		(SEASONS_MAINT_START + 22)
#define	SEASONS_MAINT_24		(SEASONS_MAINT_START + 23)
#define	SEASONS_MAINT_25		(SEASONS_MAINT_START + 24)
#define	SEASONS_MAINT_26		(SEASONS_MAINT_START + 25)
#define	SEASONS_MAINT_27		(SEASONS_MAINT_START + 26)
#define	SEASONS_MAINT_28		(SEASONS_MAINT_START + 27)
#define	SEASONS_MAINT_29		(SEASONS_MAINT_START + 28)
#define	SEASONS_MAINT_30		(SEASONS_MAINT_START + 29)
#define	SEASONS_MAINT_31		(SEASONS_MAINT_START + 30)
#define	SEASONS_MAINT_32		(SEASONS_MAINT_START + 31)
#define	SEASONS_MAINT_33		(SEASONS_MAINT_START + 32)
#define	SEASONS_MAINT_34		(SEASONS_MAINT_START + 33)
#define	SEASONS_MAINT_35		(SEASONS_MAINT_START + 34)
#define	SEASONS_MAINT_36		(SEASONS_MAINT_START + 35)
#define	SEASONS_MAINT_37		(SEASONS_MAINT_START + 36)
#define	SEASONS_MAINT_38		(SEASONS_MAINT_START + 37)
#define	SEASONS_MAINT_39		(SEASONS_MAINT_START + 38)
#define	SEASONS_MAINT_40		(SEASONS_MAINT_START + 39)
#define	SEASONS_MAINT_41		(SEASONS_MAINT_START + 40)
#define	SEASONS_MAINT_42		(SEASONS_MAINT_START + 41)
#define	SEASONS_MAINT_43		(SEASONS_MAINT_START + 42)
#define	SEASONS_MAINT_44		(SEASONS_MAINT_START + 43)
#define	SEASONS_MAINT_45		(SEASONS_MAINT_START + 44)
#define	SEASONS_MAINT_46		(SEASONS_MAINT_START + 45)
#define	SEASONS_MAINT_47		(SEASONS_MAINT_START + 46)
#define	SEASONS_MAINT_48		(SEASONS_MAINT_START + 47)
#define	SEASONS_MAINT_49		(SEASONS_MAINT_START + 48)
#define	SEASONS_MAINT_50		(SEASONS_MAINT_START + 49)
#define	SEASONS_MAINT_51		(SEASONS_MAINT_START + 50)
#define	SEASONS_MAINT_52		(SEASONS_MAINT_START + 51)
#define	SEASONS_MAINT_53		(SEASONS_MAINT_START + 52)
#define	SEASONS_MAINT_54		(SEASONS_MAINT_START + 53)
#define	SEASONS_MAINT_55		(SEASONS_MAINT_START + 54)
#define	SEASONS_MAINT_56		(SEASONS_MAINT_START + 55)
#define	SEASONS_MAINT_57		(SEASONS_MAINT_START + 56)
#define	SEASONS_MAINT_58		(SEASONS_MAINT_START + 57)
#define	SEASONS_MAINT_59		(SEASONS_MAINT_START + 58)
#define	SEASONS_MAINT_60		(SEASONS_MAINT_START + 59)
#define	SEASONS_MAINT_61		(SEASONS_MAINT_START + 60)
#define	SEASONS_MAINT_62		(SEASONS_MAINT_START + 61)
#define	SEASONS_MAINT_63		(SEASONS_MAINT_START + 62)
#define	SEASONS_MAINT_64		(SEASONS_MAINT_START + 63)
#define	SEASONS_MAINT_65		(SEASONS_MAINT_START + 64)
#define	SEASONS_MAINT_66		(SEASONS_MAINT_START + 65)
#define	SEASONS_MAINT_67		(SEASONS_MAINT_START + 66)
#define	SEASONS_MAINT_68		(SEASONS_MAINT_START + 67)
#define	SEASONS_MAINT_69		(SEASONS_MAINT_START + 68)
#define	SEASONS_MAINT_70		(SEASONS_MAINT_START + 69)
#define	SEASONS_MAINT_71		(SEASONS_MAINT_START + 70)
#define	SEASONS_MAINT_72		(SEASONS_MAINT_START + 71)
#define	SEASONS_MAINT_73		(SEASONS_MAINT_START + 72)
#define	SEASONS_MAINT_74		(SEASONS_MAINT_START + 73)
#define	SEASONS_MAINT_75		(SEASONS_MAINT_START + 74)
#define	SEASONS_MAINT_76		(SEASONS_MAINT_START + 75)
#define	SEASONS_MAINT_77		(SEASONS_MAINT_START + 76)
#define	SEASONS_MAINT_78		(SEASONS_MAINT_START + 77)
#define	SEASONS_MAINT_79		(SEASONS_MAINT_START + 78)
#define	SEASONS_MAINT_80		(SEASONS_MAINT_START + 79)
#define	SEASONS_MAINT_81		(SEASONS_MAINT_START + 80)
#define	SEASONS_MAINT_82		(SEASONS_MAINT_START + 81)
#define	SEASONS_MAINT_83		(SEASONS_MAINT_START + 82)
#define	SEASONS_MAINT_84		(SEASONS_MAINT_START + 83)
#define	SEASONS_MAINT_85		(SEASONS_MAINT_START + 84)
#define	SEASONS_MAINT_86		(SEASONS_MAINT_START + 85)
#define	SEASONS_MAINT_87		(SEASONS_MAINT_START + 86)
#define	SEASONS_MAINT_88		(SEASONS_MAINT_START + 87)
#define	SEASONS_MAINT_89		(SEASONS_MAINT_START + 88)
#define	SEASONS_MAINT_90		(SEASONS_MAINT_START + 89)
#define	SEASONS_MAINT_91		(SEASONS_MAINT_START + 90)
#define	SEASONS_MAINT_92		(SEASONS_MAINT_START + 91)
#define	SEASONS_MAINT_93		(SEASONS_MAINT_START + 92)
#define	SEASONS_MAINT_94		(SEASONS_MAINT_START + 93)
#define	SEASONS_MAINT_95		(SEASONS_MAINT_START + 94)
#define	SEASONS_MAINT_96		(SEASONS_MAINT_START + 95)
#define	SEASONS_MAINT_97		(SEASONS_MAINT_START + 96)
#define	SEASONS_MAINT_98		(SEASONS_MAINT_START + 97)
#define	SEASONS_MAINT_99		(SEASONS_MAINT_START + 98)
#define	SEASONS_MAINT_100		(SEASONS_MAINT_START + 99)
#define	SEASONS_MAINT_101		(SEASONS_MAINT_START + 100)
#define	SEASONS_MAINT_102		(SEASONS_MAINT_START + 101)
#define	SEASONS_MAINT_103		(SEASONS_MAINT_START + 102)
#define	SEASONS_MAINT_104		(SEASONS_MAINT_START + 103)
#define	SEASONS_MAINT_105		(SEASONS_MAINT_START + 104)
#define	SEASONS_MAINT_106		(SEASONS_MAINT_START + 105)
#define	SEASONS_MAINT_107		(SEASONS_MAINT_START + 106)
#define	SEASONS_MAINT_108		(SEASONS_MAINT_START + 107)
#define	SEASONS_MAINT_109		(SEASONS_MAINT_START + 108)
#define	SEASONS_MAINT_110		(SEASONS_MAINT_START + 109)
#define	SEASONS_MAINT_111		(SEASONS_MAINT_START + 110)
#define	SEASONS_MAINT_112		(SEASONS_MAINT_START + 111)
#define	SEASONS_MAINT_113		(SEASONS_MAINT_START + 112)
#define	SEASONS_MAINT_114		(SEASONS_MAINT_START + 113)
#define	SEASONS_MAINT_115		(SEASONS_MAINT_START + 114)
#define	SEASONS_MAINT_116		(SEASONS_MAINT_START + 115)
#define	SEASONS_MAINT_117		(SEASONS_MAINT_START + 116)
#define	SEASONS_MAINT_118		(SEASONS_MAINT_START + 117)
#define	SEASONS_MAINT_119		(SEASONS_MAINT_START + 118)
#define	SEASONS_MAINT_120		(SEASONS_MAINT_START + 119)
#define	SEASONS_MAINT_121		(SEASONS_MAINT_START + 120)
#define	SEASONS_MAINT_122		(SEASONS_MAINT_START + 121)
#define	SEASONS_MAINT_123		(SEASONS_MAINT_START + 122)
#define	SEASONS_MAINT_124		(SEASONS_MAINT_START + 123)
#define	SEASONS_MAINT_125		(SEASONS_MAINT_START + 124)
#define	SEASONS_MAINT_126		(SEASONS_MAINT_START + 125)
#define	SEASONS_MAINT_127		(SEASONS_MAINT_START + 126)
#define	SEASONS_MAINT_128		(SEASONS_MAINT_START + 127)
#define	SEASONS_MAINT_129		(SEASONS_MAINT_START + 128)
#define	SEASONS_MAINT_130		(SEASONS_MAINT_START + 129)
#define	SEASONS_MAINT_131		(SEASONS_MAINT_START + 130)
#define	SEASONS_MAINT_132		(SEASONS_MAINT_START + 131)
#define	SEASONS_MAINT_133		(SEASONS_MAINT_START + 132)
#define	SEASONS_MAINT_134		(SEASONS_MAINT_START + 133)
#define	SEASONS_MAINT_135		(SEASONS_MAINT_START + 134)
#define	SEASONS_MAINT_136		(SEASONS_MAINT_START + 135)
#define	SEASONS_MAINT_137		(SEASONS_MAINT_START + 136)
#define	SEASONS_MAINT_138		(SEASONS_MAINT_START + 137)
#define	SEASONS_MAINT_139		(SEASONS_MAINT_START + 138)
#define	SEASONS_MAINT_140		(SEASONS_MAINT_START + 139)
#define	SEASONS_MAINT_141		(SEASONS_MAINT_START + 140)
#define	SEASONS_MAINT_END		(SEASONS_MAINT_START + 140)

#endif




